services:
    # Students
    admin.student:
        class: 'App\Admin\StudentAdmin'
        tags:
            - { name: 'sonata.admin', manager_type: 'orm', model_class: 'App\Entity\Student', controller: 'App\Controller\Admin\StudentAdminController', label: 'Alumne', group: 'Alumnes' }
        calls:
            - [ 'setEntityManager', [ '@doctrine.orm.entity_manager' ] ]
            - [ 'setSecurityHelper', [ '@security.helper' ] ]
            - [ 'setTwigEnvironment', [ '@twig' ] ]
            - [ 'setFileService', [ '@App\Service\FileService' ] ]
            - [ 'setTemplate', [ 'edit', 'Admin/Student/edit.html.twig' ] ]
    admin.student_absence:
        class: 'App\Admin\StudentAbsenceAdmin'
        tags:
            - { name: 'sonata.admin', manager_type: 'orm', model_class: 'App\Entity\StudentAbsence', controller: 'App\Controller\Admin\StudentAbsenceAdminController', label: 'Absència alumne', group: 'Alumnes' }
        calls:
            - [ 'setEntityManager', [ '@doctrine.orm.entity_manager' ] ]
            - [ 'setSecurityHelper', [ '@security.helper' ] ]
            - [ 'setTwigEnvironment', [ '@twig' ] ]
            - [ 'setFileService', [ '@App\Service\FileService' ] ]
    admin.parent:
        class: 'App\Admin\PersonAdmin'
        tags:
            - { name: 'sonata.admin', manager_type: 'orm', model_class: 'App\Entity\Person', label: 'Pare, mare o tutor', group: 'Alumnes' }
        calls:
            - [ 'setEntityManager', [ '@doctrine.orm.entity_manager' ] ]
            - [ 'setSecurityHelper', [ '@security.helper' ] ]
            - [ 'setTwigEnvironment', [ '@twig' ] ]
            - [ 'setFileService', [ '@App\Service\FileService' ] ]
            - [ 'setTemplate', [ 'edit', 'Admin/Student/edit.html.twig' ] ]
    admin.pre_register:
        class: 'App\Admin\PreRegisterAdmin'
        tags:
            - { name: 'sonata.admin', manager_type: 'orm', model_class: 'App\Entity\PreRegister', controller: 'App\Controller\Admin\PreRegisterAdminController', label: 'Preinscipcions', group: 'Alumnes' }
        calls:
            - [ 'setEntityManager', [ '@doctrine.orm.entity_manager' ] ]
            - [ 'setSecurityHelper', [ '@security.helper' ] ]
            - [ 'setTwigEnvironment', [ '@twig' ] ]
            - [ 'setFileService', [ '@App\Service\FileService' ] ]
    admin.student_evaluation:
        class: 'App\Admin\StudentEvaluationAdmin'
        tags:
            - { name: 'sonata.admin', manager_type: 'orm', model_class: 'App\Entity\StudentEvaluation', controller: 'App\Controller\Admin\StudentEvaluationAdminController', label: 'Avaluacions', group: 'Alumnes' }
        calls:
            - [ 'setEntityManager', [ '@doctrine.orm.entity_manager' ] ]
            - [ 'setSecurityHelper', [ '@security.helper' ] ]
            - [ 'setTwigEnvironment', [ '@twig' ] ]
            - [ 'setFileService', [ '@App\Service\FileService' ] ]
    # Teachers
    admin.teacher:
        class: 'App\Admin\TeacherAdmin'
        tags:
            - { name: 'sonata.admin', manager_type: 'orm', model_class: 'App\Entity\Teacher', controller: 'App\Controller\Admin\TeacherAdminController', label: 'Professor', group: 'Professors' }
        calls:
            - [ 'setEntityManager', [ '@doctrine.orm.entity_manager' ] ]
            - [ 'setSecurityHelper', [ '@security.helper' ] ]
            - [ 'setTwigEnvironment', [ '@twig' ] ]
            - [ 'setFileService', [ '@App\Service\FileService' ] ]
    admin.teacher_absence:
        class: 'App\Admin\TeacherAbsenceAdmin'
        tags:
            - { name: 'sonata.admin', manager_type: 'orm', model_class: 'App\Entity\TeacherAbsence', label: 'Absència professor', group: 'Professors' }
        calls:
            - [ 'setEntityManager', [ '@doctrine.orm.entity_manager' ] ]
            - [ 'setSecurityHelper', [ '@security.helper' ] ]
            - [ 'setTwigEnvironment', [ '@twig' ] ]
            - [ 'setFileService', [ '@App\Service\FileService' ] ]
    # Classrooms
    admin.class_group:
        class: 'App\Admin\ClassGroupAdmin'
        tags:
            - { name: 'sonata.admin', manager_type: 'orm', model_class: 'App\Entity\ClassGroup', controller: 'App\Controller\Admin\ClassGroupAdminController', label: 'Grup', group: 'Aules' }
        calls:
            - [ 'setEntityManager', [ '@doctrine.orm.entity_manager' ] ]
            - [ 'setSecurityHelper', [ '@security.helper' ] ]
            - [ 'setTwigEnvironment', [ '@twig' ] ]
            - [ 'setFileService', [ '@App\Service\FileService' ] ]
            - [ 'setTemplate', [ 'edit', 'Admin/ClassGroup/edit.html.twig' ] ]
    admin.event:
        class: 'App\Admin\EventAdmin'
        tags:
            - { name: 'sonata.admin', manager_type: 'orm', model_class: 'App\Entity\Event', controller: 'App\Controller\Admin\EventAdminController', label: 'Horari', group: 'Aules' }
        calls:
            - [ 'setEntityManager', [ '@doctrine.orm.entity_manager' ] ]
            - [ 'setSecurityHelper', [ '@security.helper' ] ]
            - [ 'setTwigEnvironment', [ '@twig' ] ]
            - [ 'setFileService', [ '@App\Service\FileService' ] ]
            - [ 'setTemplate', [ 'edit', 'Admin/Event/edit.html.twig' ] ]
    admin.training_center:
        class: 'App\Admin\TrainingCenterAdmin'
        tags:
            - { name: 'sonata.admin', manager_type: 'orm', model_class: 'App\Entity\TrainingCenter', label: 'Centre Formació', group: 'Aules' }
        calls:
            - [ 'setEntityManager', [ '@doctrine.orm.entity_manager' ] ]
            - [ 'setSecurityHelper', [ '@security.helper' ] ]
            - [ 'setTwigEnvironment', [ '@twig' ] ]
            - [ 'setFileService', [ '@App\Service\FileService' ] ]
    # Billings
    admin.tariff:
        class: 'App\Admin\TariffAdmin'
        tags:
            - { name: 'sonata.admin', manager_type: 'orm', model_class: 'App\Entity\Tariff', label: 'Tarifa', group: 'Facturació' }
        calls:
            - [ 'setEntityManager', [ '@doctrine.orm.entity_manager' ] ]
            - [ 'setSecurityHelper', [ '@security.helper' ] ]
            - [ 'setTwigEnvironment', [ '@twig' ] ]
            - [ 'setFileService', [ '@App\Service\FileService' ] ]
    admin.receipt:
        class: 'App\Admin\ReceiptAdmin'
        tags:
            - { name: 'sonata.admin', manager_type: 'orm', model_class: 'App\Entity\Receipt', controller: 'App\Controller\Admin\ReceiptAdminController', label: 'Rebut', group: 'Facturació' }
        calls:
            - [ 'setEntityManager', [ '@doctrine.orm.entity_manager' ] ]
            - [ 'setSecurityHelper', [ '@security.helper' ] ]
            - [ 'setTwigEnvironment', [ '@twig' ] ]
            - [ 'setFileService', [ '@App\Service\FileService' ] ]
            - [ 'setTemplate', [ 'edit', 'Admin/Receipt/edit.html.twig' ] ]
            - [ 'setTemplate', [ 'list', 'Admin/Receipt/list.html.twig' ] ]
    admin.receipt_line:
        class: 'App\Admin\ReceiptLineAdmin'
        tags:
            - { name: 'sonata.admin', manager_type: 'orm', model_class: 'App\Entity\ReceiptLine', label: 'Línies rebut', group: 'Facturació', show_in_dashboard: false }
        calls:
            - [ 'setEntityManager', [ '@doctrine.orm.entity_manager' ] ]
            - [ 'setSecurityHelper', [ '@security.helper' ] ]
            - [ 'setTwigEnvironment', [ '@twig' ] ]
            - [ 'setFileService', [ '@App\Service\FileService' ] ]
    admin.receipt_group:
        class: 'App\Admin\ReceiptGroupAdmin'
        tags:
            - { name: 'sonata.admin', manager_type: 'orm', model_class: 'App\Entity\ReceiptGroup', label: 'Remeses', group: 'Facturació' }
        calls:
            - [ 'setEntityManager', [ '@doctrine.orm.entity_manager' ] ]
            - [ 'setSecurityHelper', [ '@security.helper' ] ]
            - [ 'setTwigEnvironment', [ '@twig' ] ]
            - [ 'setFileService', [ '@App\Service\FileService' ] ]
    admin.invoice:
        class: 'App\Admin\InvoiceAdmin'
        tags:
            - { name: 'sonata.admin', manager_type: 'orm', model_class: 'App\Entity\Invoice', controller: 'App\Controller\Admin\InvoiceAdminController', label: 'Factura', group: 'Facturació' }
        calls:
            - [ 'setEntityManager', [ '@doctrine.orm.entity_manager' ] ]
            - [ 'setSecurityHelper', [ '@security.helper' ] ]
            - [ 'setTwigEnvironment', [ '@twig' ] ]
            - [ 'setFileService', [ '@App\Service\FileService' ] ]
            - [ 'setTemplate', [ 'edit', 'Admin/Invoice/edit.html.twig' ] ]
    admin.invoice_line:
        class: 'App\Admin\InvoiceLineAdmin'
        tags:
            - { name: 'sonata.admin', manager_type: 'orm', model_class: 'App\Entity\InvoiceLine', label: 'Línies factura', group: 'Facturació', show_in_dashboard: false }
        calls:
            - [ 'setEntityManager', [ '@doctrine.orm.entity_manager' ] ]
            - [ 'setSecurityHelper', [ '@security.helper' ] ]
            - [ 'setTwigEnvironment', [ '@twig' ] ]
            - [ 'setFileService', [ '@App\Service\FileService' ] ]
    # Purchases
    admin.purchases.provider:
        class: 'App\Admin\ProviderAdmin'
        tags:
            - { name: 'sonata.admin', manager_type: 'orm', model_class: 'App\Entity\Provider', label: 'Proveïdor', group: 'Despeses' }
        calls:
            - [ 'setEntityManager', [ '@doctrine.orm.entity_manager' ] ]
            - [ 'setSecurityHelper', [ '@security.helper' ] ]
            - [ 'setTwigEnvironment', [ '@twig' ] ]
            - [ 'setFileService', [ '@App\Service\FileService' ] ]
    admin.purchases.spending_category:
        class: 'App\Admin\SpendingCategoryAdmin'
        tags:
            - { name: 'sonata.admin', manager_type: 'orm', model_class: 'App\Entity\SpendingCategory', label: 'Tipus Despesa', group: 'Despeses' }
        calls:
            - [ 'setEntityManager', [ '@doctrine.orm.entity_manager' ] ]
            - [ 'setSecurityHelper', [ '@security.helper' ] ]
            - [ 'setTwigEnvironment', [ '@twig' ] ]
            - [ 'setFileService', [ '@App\Service\FileService' ] ]
    admin.purchases.spending:
        class: 'App\Admin\SpendingAdmin'
        tags:
            - { name: 'sonata.admin', manager_type: 'orm', model_class: 'App\Entity\Spending', controller: 'App\Controller\Admin\SpendingAdminController', label: 'Despesa', group: 'Despeses' }
        calls:
            - [ 'setEntityManager', [ '@doctrine.orm.entity_manager' ] ]
            - [ 'setSecurityHelper', [ '@security.helper' ] ]
            - [ 'setTwigEnvironment', [ '@twig' ] ]
            - [ 'setFileService', [ '@App\Service\FileService' ] ]
    # Contacts
    admin.contact_message:
        class: 'App\Admin\ContactMessageAdmin'
        tags:
            - { name: 'sonata.admin', manager_type: 'orm', model_class: 'App\Entity\ContactMessage', controller: 'App\Controller\Admin\ContactMessageAdminController', label: 'Missatge de contacte', group: 'Contactes' }
        calls:
            - [ 'setEntityManager', [ '@doctrine.orm.entity_manager' ] ]
            - [ 'setSecurityHelper', [ '@security.helper' ] ]
            - [ 'setTwigEnvironment', [ '@twig' ] ]
            - [ 'setFileService', [ '@App\Service\FileService' ] ]
    admin.newsletter_contact:
        class: 'App\Admin\NewsletterContactAdmin'
        tags:
            - { name: 'sonata.admin', manager_type: 'orm', model_class: 'App\Entity\NewsletterContact', label: 'Butlletí de contacte', group: 'Contactes' }
        calls:
            - [ 'setEntityManager', [ '@doctrine.orm.entity_manager' ] ]
            - [ 'setSecurityHelper', [ '@security.helper' ] ]
            - [ 'setTwigEnvironment', [ '@twig' ] ]
            - [ 'setFileService', [ '@App\Service\FileService' ] ]
    # Configurations
    admin.bank_creditor_sepa:
        class: 'App\Admin\BankCreditorSepaAdmin'
        tags:
            - { name: 'sonata.admin', manager_type: 'orm', model_class: 'App\Entity\BankCreditorSepa', label: 'Banc', group: 'Configuració' }
        calls:
            - [ 'setEntityManager', [ '@doctrine.orm.entity_manager' ] ]
            - [ 'setSecurityHelper', [ '@security.helper' ] ]
            - [ 'setTwigEnvironment', [ '@twig' ] ]
            - [ 'setFileService', [ '@App\Service\FileService' ] ]
    admin.province:
        class: 'App\Admin\ProvinceAdmin'
        tags:
            - { name: 'sonata.admin', manager_type: 'orm', model_class: 'App\Entity\Province', label: 'Província', group: 'Configuració' }
        calls:
            - [ 'setEntityManager', [ '@doctrine.orm.entity_manager' ] ]
            - [ 'setSecurityHelper', [ '@security.helper' ] ]
            - [ 'setTwigEnvironment', [ '@twig' ] ]
            - [ 'setFileService', [ '@App\Service\FileService' ] ]
    admin.city:
        class: 'App\Admin\CityAdmin'
        tags:
            - { name: 'sonata.admin', manager_type: 'orm', model_class: 'App\Entity\City', label: 'Ciutat', group: 'Configuració' }
        calls:
            - [ 'setEntityManager', [ '@doctrine.orm.entity_manager' ] ]
            - [ 'setSecurityHelper', [ '@security.helper' ] ]
            - [ 'setTwigEnvironment', [ '@twig' ] ]
            - [ 'setFileService', [ '@App\Service\FileService' ] ]
    admin.user:
        class: 'App\Admin\UserAdmin'
        tags:
            - { name: 'sonata.admin', manager_type: 'orm', model_class: 'App\Entity\User', controller: 'App\Controller\Admin\UserAdminController', label: 'Usuari', group: 'Configuració' }
        calls:
            - [ 'setEntityManager', [ '@doctrine.orm.entity_manager' ] ]
            - [ 'setSecurityHelper', [ '@security.helper' ] ]
            - [ 'setTwigEnvironment', [ '@twig' ] ]
            - [ 'setFileService', [ '@App\Service\FileService' ] ]
    admin.bank:
        class: 'App\Admin\BankAdmin'
        tags:
            - { name: 'sonata.admin', manager_type: 'orm', model_class: 'App\Entity\Bank', label: 'Bank', group: 'Configuració', show_in_dashboard: false }
        calls:
            - [ 'setEntityManager', [ '@doctrine.orm.entity_manager' ] ]
            - [ 'setSecurityHelper', [ '@security.helper' ] ]
            - [ 'setTwigEnvironment', [ '@twig' ] ]
            - [ 'setFileService', [ '@App\Service\FileService' ] ]
    # Extra Helper (admins without a related entity, for extra features like file manager or calendar)
    admin.file_manager_dummy:
        class: 'App\Admin\FileDummyAdmin'
        tags:
            - { name: 'sonata.admin', manager_type: 'orm', model_class: 'App\Entity\FileDummy', controller: 'App\Controller\Admin\FileManagerAdminController', label: 'File Manager', group: 'Dummy', show_in_dashboard: false }
        calls:
            - [ 'setEntityManager', [ '@doctrine.orm.entity_manager' ] ]
            - [ 'setSecurityHelper', [ '@security.helper' ] ]
            - [ 'setTwigEnvironment', [ '@twig' ] ]
            - [ 'setFileService', [ '@App\Service\FileService' ] ]
    admin.extra_helper_manager_dummy:
        class: 'App\Admin\ExtraHelperManagerAdmin'
        tags:
            - { name: 'sonata.admin', manager_type: 'orm', model_class: 'App\Entity\ExtraHelperManager', controller: 'App\Controller\Admin\ExtraHelperManagerAdminController', label: 'Extra Manager', group: 'Dummy', show_in_dashboard: false }
        calls:
            - [ 'setEntityManager', [ '@doctrine.orm.entity_manager' ] ]
            - [ 'setSecurityHelper', [ '@security.helper' ] ]
            - [ 'setTwigEnvironment', [ '@twig' ] ]
            - [ 'setFileService', [ '@App\Service\FileService' ] ]
