artgris_file_manager:
    conf:
        default:
            dir: '%kernel.project_dir%/public/uploads/disc'
            tree: true
            # TODO add PDF & audo/video previews overriding bundle templates https://github.com/artgris/FileManagerBundle