framework:
    secret: '%env(APP_SECRET)%'
    annotations: false
    http_method_override: false
    handle_all_throwables: true
    csrf_protection: true
    esi: true
    fragments: true
    session:
        enabled: true
        handler_id: 'session.handler.native_file'
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_lifetime: 28800 # 8 hours in seconds
        cookie_secure: 'auto'
        cookie_samesite: 'lax'
        storage_factory_id: 'session.storage.factory.native'
    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: 'session.storage.factory.mock_file'
