framework:
    mailer:
        transports:
            main: '%env(MAILER_DSN)%'
            mailing: '%env(MAILING_MAILER_DSN)%'

when@dev:
    framework:
        mailer:
            envelope:
                recipients: [ '%delivery_dev_address%' ]

when@test:
    framework:
        mailer:
            dsn: 'null://null'
