framework:
    messenger:
        failure_transport: 'failed'
        reset_on_message: true
        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'
        routing:
            App\Message\NewReceiptCreatedEmailMessage: 'async'
            Symfony\Component\Mailer\Messenger\SendEmailMessage: 'async'
