security:
    role_hierarchy:
        ROLE_SONATA_CMS:
            - 'ROLE_ADMIN_APP_TEACHER_ALL'
            - 'ROLE_ADMIN_APP_CONTACTMESSAGE_ALL'
            - 'ROLE_ADMIN_APP_NEWSLETTERCONTACT_ALL'
        ROLE_SONATA_MANAGER:
            - 'ROLE_ADMIN_APP_CONTACTMESSAGE_ALL'
            - 'ROLE_ADMIN_APP_TEACHER_ALL'
            - 'ROLE_ADMIN_APP_TEACHER_ABSENCE_ALL'
            - 'ROLE_ADMIN_APP_CLASS_GROUP_ALL'
            - 'ROLE_ADMIN_APP_EVENT_ALL'
            - 'ROLE_ADMIN_APP_STUDENT_ALL'
            - 'ROLE_ADMIN_APP_STUDENT_ABSENCE_ALL'
            - 'ROLE_ADMIN_APP_PARENT_ALL'
            - 'ROLE_ADMIN_APP_BANK_ALL'
            - 'ROLE_ADMIN_APP_PRE_REGISTER_ALL'
            - 'ROLE_ADMIN_APP_FILE_MANAGER_DUMMY_ALL'
        ROLE_SONATA_CUSTOM_ADMIN:
            - 'ROLE_ADMIN_APP_BANK_CREDITOR_SEPA_ALL'
            - 'ROLE_ADMIN_APP_NEWSLETTERCONTACT_ALL'
            - 'ROLE_ADMIN_APP_RECEIPT_ALL'
            - 'ROLE_ADMIN_APP_RECEIPT_LINE_ALL'
            - 'ROLE_ADMIN_APP_RECEIPT_GROUP_LIST'
            - 'ROLE_ADMIN_APP_RECEIPT_GROUP_DELETE'
            - 'ROLE_ADMIN_APP_INVOICE_ALL'
            - 'ROLE_ADMIN_APP_INVOICE_LINE_ALL'
            - 'ROLE_ADMIN_APP_TARIFF_ALL'
            - 'ROLE_ADMIN_APP_PURCHASES_PROVIDER_ALL'
            - 'ROLE_ADMIN_APP_PURCHASES_SPENDING_CATEGORY_ALL'
            - 'ROLE_ADMIN_APP_PURCHASES_SPENDING_ALL'
            - 'ROLE_ADMIN_APP_PROVINCE_ALL'
            - 'ROLE_ADMIN_APP_CITY_ALL'
            - 'ROLE_ADMIN_APP_USER_ALL'
        ROLE_CMS:
            - 'ROLE_USER'
            - 'ROLE_SONATA_CMS'
            - 'ROLE_SONATA_ADMIN'
        ROLE_MANAGER:
            - 'ROLE_USER'
            - 'ROLE_SONATA_ADMIN'
            - 'ROLE_SONATA_MANAGER'
        ROLE_ADMIN:
            - 'ROLE_MANAGER'
            - 'ROLE_SONATA_CUSTOM_ADMIN'
        ROLE_SUPER_ADMIN:
            - 'ROLE_ADMIN'
            - 'ROLE_ADMIN_APP_TRAINING_CENTER_ALL'
            - 'ROLE_ALLOWED_TO_SWITCH'
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: 'App\Entity\User'
                property: 'email'
    firewalls:
        dev:
            pattern: '^/(_(profiler|wdt)|css|images|js)/'
            security: false
        admin:
            lazy: true
            pattern: '/admin(.*)'
            provider: 'app_user_provider'
            entry_point: 'form_login'
            form_login:
                login_path:            'admin_app_login'
                check_path:            'admin_app_login'
                username_parameter:    'admin_login_form[username]'
                password_parameter:    'admin_login_form[password]'
                target_path_parameter: 'admin_login_form[target_path]'
                csrf_parameter:        '_csrf_token'
            logout:
                path:   '/admin/logout'
                target: '/admin/login'
        frontend:
            pattern: '^/(.*)'
            context: 'user'
            lazy:    true
    access_control:
        - { path: ^/admin/login$, role: 'PUBLIC_ACCESS' }
        - { path: ^/admin/resetting, role: 'PUBLIC_ACCESS' }
        - { path: ^/admin/, role: 'ROLE_USER' }
        - { path: ^/.*, role: 'PUBLIC_ACCESS' }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm:   auto
                cost:        4
                time_cost:   3
                memory_cost: 10
        firewalls:
            admin:
                http_basic: ~
