security:
    enable_authenticator_manager: true
    role_hierarchy:
        ROLE_SONATA_CMS:
            - ROLE_ADMIN_TEACHER_ALL
            - ROLE_ADMIN_SERVICE_ALL
            - ROLE_ADMIN_CONTACTMESSAGE_ALL
            - ROLE_ADMIN_NEWSLETTERCONTACT_ALL
        ROLE_SONATA_MANAGER:
            - ROLE_ADMIN_CONTACTMESSAGE_ALL
            - ROLE_ADMIN_TEACHER_ALL
            - ROLE_ADMIN_TEACHER_ABSENCE_ALL
            - ROLE_ADMIN_CLASS_GROUP_ALL
            - ROLE_ADMIN_EVENT_ALL
            - ROLE_ADMIN_STUDENT_ALL
            - ROLE_ADMIN_STUDENT_ABSENCE_ALL
            - ROLE_ADMIN_PARENT_ALL
            - ROLE_ADMIN_BANK_ALL
            - ROLE_ADMIN_PRE_REGISTER_ALL
            - ROLE_ADMIN_FILE_MANAGER_DUMMY_ALL
        ROLE_SONATA_CUSTOM_ADMIN:
            - ROLE_ADMIN_BANK_CREDITOR_SEPA_ALL
            - ROLE_ADMIN_SERVICE_ALL
            - ROLE_ADMIN_NEWSLETTERCONTACT_ALL
            - ROLE_ADMIN_RECEIPT_ALL
            - ROLE_ADMIN_RECEIPT_LINE_ALL
            - ROLE_ADMIN_INVOICE_ALL
            - ROLE_ADMIN_INVOICE_LINE_ALL
            - ROLE_ADMIN_TARIFF_ALL
            - ROLE_ADMIN_PURCHASES_PROVIDER_ALL
            - ROLE_ADMIN_PURCHASES_SPENDING_CATEGORY_ALL
            - ROLE_ADMIN_PURCHASES_SPENDING_ALL
            - ROLE_ADMIN_PROVINCE_ALL
            - ROLE_ADMIN_CITY_ALL
            - ROLE_ADMIN_USER_ALL
        ROLE_CMS:
            - ROLE_USER
            - ROLE_SONATA_CMS
            - ROLE_SONATA_ADMIN
        ROLE_MANAGER:
            - ROLE_USER
            - ROLE_SONATA_ADMIN
            - ROLE_SONATA_MANAGER
        ROLE_ADMIN:
            - ROLE_MANAGER
            - ROLE_SONATA_CUSTOM_ADMIN
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - ROLE_ALLOWED_TO_SWITCH
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class:    'App\Entity\User'
                property: 'username'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: /admin(.*)
            lazy:    true
            form_login:
                provider:                       'app_user_provider'
                login_path:                     /admin/login
                use_forward:                    false
                check_path:                     /admin/login_check
                failure_path:                   /admin/login
                default_target_path:            /admin/dashboard
                always_use_default_target_path: true
                use_referer:                    true
            logout:
                path:   /admin/logout
                target: /admin/login
        frontend:
            pattern: ^/(.*)
            context: user
            lazy:    true
    access_control:
#        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/admin/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/admin/, role: ROLE_USER }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm:   auto
                cost:        4
                time_cost:   3
                memory_cost: 10
