sonata_admin:
    title:              '%project_backend_title%'
    title_logo:         '%admin_logo%'
    persist_filters:    true
    show_mosaic_button: false
    search:             false
    options:
        form_type: 'standard'
        default_icon: 'fas fa-folder'
        logo_content: 'icon'
        list_action_button_content: 'icon'
        html5_validate: true
        confirm_exit:   true
        use_select2:    true
        use_icheck:     true
        pager_links:    10
    security:
        handler:          'sonata.admin.security.handler.role'
        role_admin:       'ROLE_ADMIN'
        role_super_admin: 'ROLE_ADMIN'
    templates:
        layout:        'Admin/layout.html.twig'
        list:          'Admin/list.html.twig'
        edit:          'Admin/edit.html.twig'
        show:          'Admin/show.html.twig'
        batch:         'Admin/batch.html.twig'
        pager_results: 'Admin/results.html.twig'
    dashboard:
        groups:
            Alumnes:
                icon:     '<i class="fa fa-graduation-cap"></i>'
                provider: 'backend_students_menu'
            Professors:
                icon:     '<i class="fa fa-user"></i>'
            Aules:
                icon:     '<i class="fa fa-window-maximize"></i>'
            Facturaci贸:
                icon:     '<i class="fa fa-eur"></i>'
                provider: 'backend_invoice_menu'
                roles:    [ 'ROLE_ADMIN' ]
            Despeses:
                icon:     '<i class="fa fa-eur"></i>'
                roles:    [ 'ROLE_ADMIN' ]
            Fitxers:
                icon:     '<i class="fa fa-file"></i>'
                provider: 'backend_files_manager_menu'
                roles:    [ 'ROLE_MANAGER' ]
            Contactes:
                icon:     '<i class="fa fa-envelope"></i>'
            Configuraci贸:
                icon:     '<i class="fa fa-cogs"></i>'
        blocks:
            -
                position: 'top'
                type:     'sonata.block.service.text'
                class:    'col-xs-12'
                roles:    [ 'ROLE_CMS' ]
                settings:
                    content: >
                        <h1 style='margin-top:0'>%project_backend_title%</h1>
            -
                position: 'top'
                type:     'App\Block\EventCalendarBlock'
                class:    'col-xs-12'
                roles:    [ 'ROLE_MANAGER' ]
            -
                position: 'top'
                type:     'App\Block\ChartsBlock'
                class:    'col-xs-12'
                roles:    [ 'ROLE_ADMIN' ]

when@dev:
    sonata_admin:
        dashboard:
            groups:
                Alumnes:
                    keep_open: true
                Professors:
                    keep_open: true
                Aules:
                    keep_open: true
                Facturaci贸:
                    keep_open: true
                Despeses:
                    keep_open: true
                Fitxers:
                    keep_open: true
                Contactes:
                    keep_open: true
                Configuraci贸:
                    keep_open: true
