imports:
    - { resource: 'services/repositories.yaml' }
    - { resource: 'services/admins.yaml' }

parameters:
    default_locale:           '%env(string:DEFAULT_LOCALE)%'
    database_server_version:  '%env(resolve:DATABASE_SERVER_VERSION)%'
    project_web_title:        '%env(string:PROJECT_WEB_TITLE)%'
    project_url_base:         '%env(string:PROJECT_BASE_URL)%'
    google_analytics_enabled: '%env(bool:GOOGLE_ANALYTICS_IS_ENABLED)%'
    google_analytics_account: '%env(string:GOOGLE_ANALYTICS_ACCOUNT)%'
    google_maps_api_key:      '%env(string:GOOGLE_MAPS_API_KEY)%'
    delivery_dev_address:     '%env(string:DEV_DELIVERY_ADDRESS)%'

services:
    _defaults:
        autowire:      true
        autoconfigure: true
    App\:
        resource: '../src/*'
        exclude:  '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
    App\Controller\:
        resource: '../src/Controller'
        tags:     ['controller.service_arguments']
