- name: fix symfony logs directory apache ownership
  file:
    recurse: yes
    force:   yes
    path:    "{{ ansistrano_deploy_to }}/shared/var/log"
    owner:   "{{ remote_system_user }}"
    group:   "{{ remote_system_group }}"
- name: fix symfony sessions directory apache ownership
  file:
    path: "{{ ansistrano_deploy_to }}/shared/var/sessions"
    recurse: yes
    owner: "{{ remote_system_user }}"
    group: "{{ remote_system_group }}"
