- name: fix symfony web directory apache ownership
  file:
    path: "{{ ansistrano_release_path.stdout }}/public"
    recurse: yes
    follow: yes
    owner: "{{ remote_system_user }}"
    group: "{{ remote_system_group }}"
- name: reloaded apache service
  service:
    state: reloaded
    name: "php{{ vhost_php_version }}-fpm"
