- name: stop messenger subsystem async workers
  shell: "supervisorctl stop boxidiomes-messenger-consume:*"
- name: copy .env production file
  copy:
    src:  "{{ playbook_dir }}/vars/.env.prod"
    dest: "{{ ansistrano_release_path.stdout }}/.env"
